<?php
$top_nav=array(
    'en'=>array('Characteristics', 'Media', 'Comments', 'Accessories', 'Compare', 'Contacts'),
    'ru'=>array('Характеристики', 'Медиа', 'Комментарии', 'Аксессуары', 'Сравнить', 'Контакты'),
    'sk'=>array('Charakteristiky', 'Médiá', 'Komentáre', 'Doplnky', 'Porovnať', 'Kontakty')
);

$index_tex=array(
    'en'=>array('Iphone 6s was first introduced to the market in September 2015, and since then has gained a wide popularity among users. The simple yet modern design has brought a lot of attention to it. Users loved it for its convenience: it’s not too small, like Iphone 4, and not as big as its brother Iphone 6s Plus. Available in 4 defferent colours, it can fullfill the preferences of everyone. Two cameras with 12 and 5 megapixels allow users to take good quality pictures and selfies. And lets not forget about the variety of available accessories for this specific model.','
        Iphone 6S can be found with several memory capacities: 16, 32, 64 and 128 GB. If we compare it to the Iphone 6, the models do look alike, but the Iphone 6S has improved hardware, including a strengthened chassis and upgraded system-on-chip. The fingerprint recognition sensor system has also been updated for this model.', 'If talking about significant features it would be stupid not to mention that Iphone 6S was the last model to have a standard 3.5 mm stereo headphone jack, which makes it more convenient, for example, when you want to charge your phone and listen to music at the same time.', 'Currently Apple Inc doesn’t produce this specific model. Its production stopped in 2018 with the release of the Iphone XR. But if you ever decide to buy this phone, it can still be found on the market.'),
    'ru'=>array('Iphone 6s был впервые представлен на рынке в сентябре 2015 года, и с тех пор приобрел большую популярность среди пользователей. Простой, но совеменный дизайн привлек к нему большое внимание. Пользователи оценили его удобство: он не такой маленький, как Iphone 4, и не такой большой, как его старший брат Iphone 6s Plus. Доступный в 4 цветах, он может удовлетворить предпочтения любого. Две камеры с 12 и 5 мегапикселями позволяют пользователям делать фотографии и селфи хорошего качества. И давайте не будем забывать о разнообразии аксессуаров, доступных для этой модели.', 'Варианты данной модели представлены 4 размерами памяти: 16, 32, 64 и 128 ГБ. Если сравнивать его с Iphone 6, то модели похожи, но у Iphone 6s улучшена аппаратная составляющая и улучшенный встроенный чип. Система распознавания отпечатка пальца для данной модели также была усовершенствована.', 'Если уж говорить об отличительных особенностях, то будет глупо не упомянуть, что Iphone 6s был последней моделью, у которой был стандартный разъём 3,5 мм, который делает данную модель значительно более удобной, например, когда есть необходимость одновременно зарядить телефон и послушать музыку.','Сейчас компания "Apple" не выпускает телефоны данной модели. Их производство прекратилось в 2018 после выпуска на рынок Iphone XR. Но, если вдруг вы решите приобрести данную модель, ее все еще можно найти в продаже.'),
    'sk'=>array('Iphone 6s bol prvýkrát uvedený na trh v septembri 2015 a od tej doby si získal veľkú popularitu medzi používateľmi. Jednoduchý, ale moderný dizajn mu priniesol veľkú pozornosť. Používateľom sa to páčilo pre jeho pohodlie: nie je príliš malý, ako napríklad Iphone 4, a nie taký veľký ako jeho brat Iphone 6s Plus. Je k dispozícii v 4 rôznych farbách a môže naplniť preferencie každého. Dva fotoaparáty s rozlíšením 12 a 5 megapixelov umožňujú používateľom robiť kvalitné fotografie a selfie. A nezabúdajme na rozmanitosť dostupného príslušenstva pre tento konkrétny model.','
        Iphone 6S možno nájsť s niekoľkými kapacitami pamäte: 16, 32, 64 a 128 GB. Ak to porovnáme s Iphone 6, všetky modely sa na seba podobajú, ale Iphone 6S má vylepšený hardvér vrátane posilneného šasi a vylepšeného systému na čipe. Pre tento model bol tiež aktualizovaný systém snímačov rozpoznávania odtlačkov prstov.', 'Ak hovoríme o významných vlastnostiach, bolo by hlúpe nehovoriac o tom, že Iphone 6S bol posledným modelom so štandardným 3,5 mm stereofónnym konektorom pre slúchadlá, čo je pohodlnejšie, napríklad keď chcete nabíjať telefón a počúvať hudbu na rovnaký čas.', 'Spoločnosť Apple Inc v súčasnosti tento konkrétny model nevyrába. Jeho výroba sa zastavila v roku 2018 vydaním Iphone XR. Ale ak sa niekedy rozhodnete kúpiť tento telefón, stále sa dá nájsť na trhu.')
);
?>