<?php
$top_nav=array(
    'en'=>array('Characteristics', 'Media', 'Comments', 'Accessories', 'Compare', 'Contacts'),
    'ru'=>array('Характеристики', 'Медиа', 'Комментарии', 'Аксессуары', 'Сравнить', 'Контакты'),
    'sk'=>array('Charakteristiky', 'Médiá', 'Komentáre', 'Doplnky', 'Porovnať', 'Kontakty')
);

$index_tex=array(
    'en'=>array('Iphone 6s was first introduced to the market in September 2015, and since then has gained a wide popularity among users. The simple yet modern design has brought a lot of attention to it. Users loved it for its convenience: it’s not too small, like Iphone 4, and not as big as its brother Iphone 6s Plus. Available in 4 defferent colours, it can fullfill the preferences of everyone. Two cameras with 12 and 5 megapixels allow users to take good quality pictures and selfies. And lets not forget about the variety of available accessories for this specific model.','
        Iphone 6S can be found with several memory capacities: 16, 32, 64 and 128 GB. If we compare it to the Iphone 6, the models do look alike, but the Iphone 6S has improved hardware, including a strengthened chassis and upgraded system-on-chip. The fingerprint recognition sensor system has also been updated for this model.', 'If talking about significant features it would be stupid not to mention that Iphone 6S was the last model to have a standard 3.5 mm stereo headphone jack, which makes it more convenient, for example, when you want to charge your phone and listen to music at the same time.', 'Currently Apple Inc doesn’t produce this specific model. Its production stopped in 2018 with the release of the Iphone XR. But if you ever decide to buy this phone, it can still be found on the market.'),
    'ru'=>array('Iphone 6s был впервые представлен на рынке в сентябре 2015 года, и с тех пор приобрел большую популярность среди пользователей. Простой, но совеменный дизайн привлек к нему большое внимание. Пользователи оценили его удобство: он не такой маленький, как Iphone 4, и не такой большой, как его старший брат Iphone 6s Plus. Доступный в 4 цветах, он может удовлетворить предпочтения любого. Две камеры с 12 и 5 мегапикселями позволяют пользователям делать фотографии и селфи хорошего качества. И давайте не будем забывать о разнообразии аксессуаров, доступных для этой модели.', 'Варианты данной модели представлены 4 размерами памяти: 16, 32, 64 и 128 ГБ. Если сравнивать его с Iphone 6, то модели похожи, но у Iphone 6s улучшена аппаратная составляющая и улучшенный встроенный чип. Система распознавания отпечатка пальца для данной модели также была усовершенствована.', 'Если уж говорить об отличительных особенностях, то будет глупо не упомянуть, что Iphone 6s был последней моделью, у которой был стандартный разъём 3,5 мм, который делает данную модель значительно более удобной, например, когда есть необходимость одновременно зарядить телефон и послушать музыку.','Сейчас компания "Apple" не выпускает телефоны данной модели. Их производство прекратилось в 2018 после выпуска на рынок Iphone XR. Но, если вдруг вы решите приобрести данную модель, ее все еще можно найти в продаже.'),
    'sk'=>array('Iphone 6s bol prvýkrát uvedený na trh v septembri 2015 a od tej doby si získal veľkú popularitu medzi používateľmi. Jednoduchý, ale moderný dizajn mu priniesol veľkú pozornosť. Používateľom sa to páčilo pre jeho pohodlie: nie je príliš malý, ako napríklad Iphone 4, a nie taký veľký ako jeho brat Iphone 6s Plus. Je k dispozícii v 4 rôznych farbách a môže naplniť preferencie každého. Dva fotoaparáty s rozlíšením 12 a 5 megapixelov umožňujú používateľom robiť kvalitné fotografie a selfie. A nezabúdajme na rozmanitosť dostupného príslušenstva pre tento konkrétny model.','
        Iphone 6S možno nájsť s niekoľkými kapacitami pamäte: 16, 32, 64 a 128 GB. Ak to porovnáme s Iphone 6, všetky modely sa na seba podobajú, ale Iphone 6S má vylepšený hardvér vrátane posilneného šasi a vylepšeného systému na čipe. Pre tento model bol tiež aktualizovaný systém snímačov rozpoznávania odtlačkov prstov.', 'Ak hovoríme o významných vlastnostiach, bolo by hlúpe nehovoriac o tom, že Iphone 6S bol posledným modelom so štandardným 3,5 mm stereofónnym konektorom pre slúchadlá, čo je pohodlnejšie, napríklad keď chcete nabíjať telefón a počúvať hudbu na rovnaký čas.', 'Spoločnosť Apple Inc v súčasnosti tento konkrétny model nevyrába. Jeho výroba sa zastavila v roku 2018 vydaním Iphone XR. Ale ak sa niekedy rozhodnete kúpiť tento telefón, stále sa dá nájsť na trhu.')
);

$buy_tex=array('en'=>array('Height:','5.44 inches (138.3 mm)', '5.44 inches (138.3 mm)', '5.45 inches (138.4 mm)', 'Width:', '2.64 inches (67.1 mm)', '2.64 inches (67.1 mm)', '2.65 inches (67.3 mm)', 'Depth:', '0.28 inch (7.1 mm)', '0.28 inch (7.1 mm)', '0.29 inch (7.3 mm)', 'Weight:', '5.04 ounces (143 grams)', '4.87 ounces (138 grams)', '5.22 ounces (148 grams)'),
    'ru'=>array('Длина:','138,3 мм', '138,3 мм', '138,4 мм', 'Ширина:', '67,1 мм', '67,1 мм', '67,3 мм', 'Толщина:', '7,1 мм', '7,1 мм', '7,3 мм', 'Вес:', '143 г', '138 г', '148 г'),
    'sk'=>array('Výška:','138.3 mm', '138.3 mm', '138.4 mm', 'Šírka:', '67.1 mm', '67.1 mm', '67.3 mm', 'Hrúbka:', '7.1 mm', '7.1 mm', '7.3 mm', 'Hmotnosť:', '143 grams', '138 grams', '148 grams')
);
               
$charact=array('en'=>array('Colors:','Rose Gold', 'Gold', 'Silver', 'Space Gray', 'Capacity:', 'Display:', 'Retina HD display with 3D Touch', '4.7-inch (diagonal) widescreen LCD Multi-Touch display with IPS technology', '1334-by-750-pixel resolution at 326 ppi', '1400:1 contrast ratio (typical)', '500 cd/m2 max brightness (typical)', 'Full sRGB standard', 'Dual-domain pixels for wide viewing angles', 'Fingerprint-resistant oleophobic coating on front', 'Support for display of multiple languages and characters simultaneously', 'Display Zoom', 'Reachability', 'Chip:', 'A9 chip with 64-bit architecture', 'Embedded M9 motion coprocessor', 'Camera:', '12-megapixel camera', 'Live Photos with stabilization', 'Autofocus with Focus Pixels', 'True Tone flash', 'Panorama (up to 63 megapixels)', 'Auto HDR for photos', 'Exposure control', 'Burst mode', 'Timer mode', 'Five-element lens', '5x digital zoom', 'Hybrid IR filter', 'Backside illumination sensor', 'Sapphire crystal lens cover', 'Auto image stabilization', 'Local tone mapping', 'Noise reduction', 'Face detection', 'Photo geotagging', 'Video Recording:', '4K video recording at 30 fps', '1080p HD video recording at 30 fps or 60 fps', '720p HD video recording at 30 fps', 'True Tone flash', 'Slo-mo video support for 1080p at 120 fps and 720p at 240 fps', 'Time-lapse video with stabilization', 'Cinematic video stabilization (1080p and 720p)', 'Continuous autofocus video', 'Noise reduction', 'Take 8-megapixel still photos while recording 4K video', 'Playback zoom', '3x digital zoom', 'Face detection', 'Video geotagging', 'Power and Battery:', 'Talk time: Up to 14 hours on 3G', 'Internet use: Up to 10 hours on 3G, up to 10 hours on LTE, up to 11 hours on Wi-Fi', 'HD video playback: Up to 11 hours', 'Audio playback: Up to 50 hours', 'Standby time: Up to 10 days', 'Built-in rechargeable lithium-ion battery', 'Charging via USB to computer system or power adapter', 'Sensors:', 'Touch ID fingerprint sensor', 'Barometer', 'Three-axis gyro', 'Accelerometer', 'Proximity sensor', 'Ambient light sensor', 'Operating System:', 'iOS 11', 'SIM Card:', 'Nano-SIM'),
    'ru'=>array('Цвет:','«Розовое золото»', 'золотой', 'серебристый', '«серый космос»', 'Ёмкость:', 'Дисплей:', 'Дисплей Retina HD с технологией 3D Touch', 'Широкоформатный ЖК‑дисплей Multi‑Touch с диагональю 4,7 дюйма и технологией IPS', '1334x750 пикселей, 326 пикселей/дюйм', 'Контрастность 1400:1 (стандартная)', 'Яркость до 500 кд/м² (стандартная)', 'Полная поддержка стандарта sRGB', 'Двухдоменные пиксели для расширения угла просмотра', 'Олеофобное покрытие на передней панели, устойчивое к появлению следов от пальцев', 'Поддержка одновременного отображения нескольких языков и наборов символов', 'Масштабирование экрана', 'Удобный доступ', 'Процессор:', 'Процессор A9 с 64-битной архитектурой', 'Встроенный сопроцессор движения М9', 'Камера:', 'Камера 12 Мп', 'Live Photos со стабилизацией изображения', 'Автофокус (технология Focus Pixels)', 'Вспышка True Tone', 'Панорамная съёмка (до 63 мегапикселей)', 'Автоматическое включение HDR при фотосъёмке', 'Контроль экспозиции', 'Серийная съëмка', 'Режим таймера', 'Пятилинзовый объектив', '5-кратный цифровой зум', 'Гибридный ИК-фильтр', 'Сенсор BSI', 'Объектив защищён сапфировым стеклом', 'Автоматическая стабилизация изображения', 'Система тональной компрессии', 'Шумоподавление', 'Распознавание лиц', 'PПривязка фотографий к месту съёмки', 'Запись видео:', 'Запись видео 4K с частотой 30 кадров/с', 'Запись HD-видео 1080p с частотой 30 или 60 кадров/с', 'Запись HD-видео 720p с частотой 30 кадров/с', 'Вспышка True Tone', 'Поддержка съёмки замедленного видео с разрешением 1080р и частотой 120 кадров/с или с разрешением 720р и частотой 240 кадров/с', 'Режим покадровой съёмки со стабилизацией изображения', 'Кинематографическая стабилизация видео (1080p и 720p)', 'Следящий автофокус', 'Шумоподавление', 'Возможность съёмки фотографий 8 Мп во время записи видео 4K', 'Увеличение при воспроизведении', '3-кратный цифровой зум', 'Распознавание лиц', 'Привязка видео к месту съёмки', 'Питание и аккумулятор:', 'Время работы в режиме разговора: до 14 часов в сети 3G', 'Время работы в интернете: до 10 часов в сети 3G, до 10 часов в сети 4G LTE, до 11 часов через Wi‑Fi', 'Время воспроизведения HD‑видео: до 11 часов', 'Время воспроизведения музыки: до 50 часов', 'Время работы в режиме ожидания: до 10 дней', 'Встроенный литий-ионный аккумулятор', 'Зарядка через USB от компьютера или адаптера питания', 'Датчики:', 'Датчик идентификации по отпечатку пальца Touch ID', 'Барометр', 'Трёхосевой гироскоп', 'Акселерометр', 'Датчик приближения', 'Датчик внешней освещённости', 'Операционная система:', 'iOS 11', 'SIM-карта:', 'Nano-SIM'),
    'sk'=>array('Farba:','Ružovozlatá', 'Zlatá', 'Strieborná', 'Kozmická sivá', 'Kapacita:', 'Displej:', 'Displej Retina HD s technológiou 3D Touch', '4,7-palcový (diagonálne) širokouhlý displej LCD Multi-Touch s technológiou IPS', 'Rozlíšenie 1 334 x 750 pixlov pri 326 ppi', 'Kontrastný pomer 1 400 : 1 (zvyčajný)', 'Maximálny jas 500 cd/m2 (zvyčajný)', 'Plnohodnotný štandard sRGB', 'Pixle s technológiou dual domain na zlepšenie viditeľnosti obsahu na displeji pri pohľade z uhla', 'Oleofóbna povrchová úprava na prednej strane, odolná voči odtlačkom', 'Podpora pre súčasné zobrazovanie viacerých jazykov a znakov', 'Nastaviteľný zoom displeja', 'Nastavenie dosiahnuteľnosti prvkov na displeji', 'Čip:', 'Čip A9 so 64-bitovou architektúrou', 'Vstavaný pohybový koprocesor M9', 'Kamera:', '12 Mpx kamera', 'Live Photos so stabilizáciou', 'Automatické zaostrovanie s technológiou Focus Pixels', 'Blesk True Tone Flash', 'Panoráma (až 63 megapixlov)', 'Automatické HDR pre fotky', 'Ovládanie expozície', 'Režim nepretržitého snímania', 'Režim časovača', 'Päťdielny objektív', '5x digitálny zoom', 'Hybridný infračervený filter', 'Senzor BSI', 'Kryt objektívu zo zafírového kryštálu', 'Automatická stabilizácia obrazu', 'Lokálne mapovanie odtieňov', 'Redukcia šumu', 'Rozpoznávanie tvárí', 'Geotagging fotiek', 'Nahrávanie videa:', 'Nahrávanie 4K videa pri 30 snímkach/s', 'Nahrávanie 1 080p HD videa pri 30 alebo 60 snímkach/s', 'Nahrávanie 720p HD videa pri 30 snímkach/s', 'Blesk True Tone Flash', 'Podpora pre spomalené video s rozlíšením 1 080p pri 120 snímkach/s a s rozlíšením 720p pri 240 snímkach/s', 'Časozberné video so stabilizáciou', 'Filmová stabilizácia videa (1 080p a 720p)', 'Video s nepretržitým automatickým zaostrovaním', 'Redukcia šumu', 'Snímanie 8 Mpx fotiek počas nahrávania 4K videa', 'Zoomovanie pri prehrávaní', '3-násobný zoom', 'Rozpoznávanie tvárí', 'Geotagging videí', 'Napájanie a batéria:', 'Čas hovoru: až do 14 hodín v sieti 3G', 'Používanie internetu: až do 10 hodín v sieti 3G a 11 hodín v sieti Wi‑Fi', 'Prehrávanie HD videa: až do 11 hodín', 'Prehrávanie zvuku: až do 50 hodín', 'Pohotovostný režim: až do 10 dní', 'Vstavaná nabíjateľná lítiovo-iónová batéria', 'Nabíjanie prostredníctvom rozhrania USB z počítača alebo napájacieho adaptéra', 'Senzory:', 'Senzor odtlačku prsta Touch ID', 'Barometer', 'Trojosový gyroskop', 'Akcelerometer', 'Senzor blízkosti', 'Senzor okolitého svetla', 'Operačný systém:', 'iOS 11', 'SIM karta:', 'Nano-SIM')
              );

$media=array('en'=>array('Media/covers/media_cover_1.jpg','Media/covers/media_cover_3.jpg', 'Media/covers/media_cover_4.jpg', 'Media/covers/media_cover_2.jpg'),
             'ru'=>array('Media/covers/cover_rus_2.jpg', 'Media/covers/cover_rus_3.jpg', 'Media/covers/cover_rus_4.jpg', 'Media/covers/cover_rus_1.jpg'),
             'sk'=>array('Media/covers/cover_sk_2.jpg', 'Media/covers/cover_sk_3.jpg', 'Media/covers/cover_sk_4.jpg', 'Media/covers/cover_sk_1.jpg')
            );
?>

